<div
     style="padding: 20px;
            color: white;
            font-size: 250%;
            text-align: center;
            display: fill;
            border-radius: 5px;
            background-color: #2a2a9fab;
            overflow: hidden;
            font-weight: 700;
            border: 5px solid #bebe0d;"
     >
Predicting Electricity Tariff for Electricity Customers - Regression
</div>

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Load Data</b></p>
</div>

In [ ]:
# Import Libraries
import pandas as pd 
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report, confusion_matrix
  

from math import sqrt

df = pd.read_csv("energy_data.csv")
# df.head() - preview the data

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Prepare the Data for Regression ML</b></p>
</div>

In [5]:
df.columns

Index(['Age', 'MaritalStatus', 'AnnualConsumption', 'DayNightConsumption',
       'IncomeLevel', 'DwellingArea', 'HasChildren', 'SolarRoof',
       'ShiftableLoad', 'RiskAttitude', 'AttitudeSustainability', 'Tariff'],
      dtype='str')

In [6]:
features = ['Age', 'MaritalStatus', 'DayNightConsumption',
       'IncomeLevel', 'DwellingArea', 'HasChildren', 'SolarRoof',
       'ShiftableLoad', 'RiskAttitude', 'AttitudeSustainability', 'Tariff']

In [7]:
target = ['AnnualConsumption']

In [8]:
# Extract Features and Target ('overall_rating') Values into Separate Dataframes
X = df[features]
y = df[target]

In [9]:
# Let us look at a typical row from our features:
X.iloc[2]

Age                             64
MaritalStatus                    6
DayNightConsumption       0.785733
IncomeLevel                      2
DwellingArea                     4
HasChildren                  False
SolarRoof                     True
ShiftableLoad                    2
RiskAttitude                 False
AttitudeSustainability           2
Tariff                    Tariff 2
Name: 2, dtype: object

In [10]:
# create dummy variables for categorical columsn
X = pd.get_dummies(X,drop_first=True)
X.head()

,Age,MaritalStatus,DayNightConsumption,IncomeLevel,DwellingArea,HasChildren,SolarRoof,ShiftableLoad,RiskAttitude,AttitudeSustainability,Tariff_Tariff 2,Tariff_Tariff 3
0,60,4,0.811033,4,3,False,True,3,True,1,False,True
1,43,4,0.464281,1,1,False,False,3,False,1,False,False
2,64,6,0.785733,2,4,False,True,2,False,2,True,False
3,44,6,0.618946,3,1,False,True,3,True,3,False,False
4,19,5,0.281707,2,1,True,False,4,False,2,False,False

In [11]:
# Let us look at a typical row from our features:
y

     AnnualConsumption
0                 4420
1                 4127
2                 4564
3                 3689
4                 5311
..                 ...
995               2514
996               4766
997               4360
998               5345
999               3492

[1000 rows x 1 columns]

In [12]:
# split data into training (70%) and testing (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=50)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Linear Regressor</b></p>
</div>

In [13]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_prediction = regressor.predict(X_test)
# y_prediction

In [14]:
# Mean of the expected target value in test set
y_test.describe()

       AnnualConsumption
count         300.000000
mean         3864.566667
std           972.304217
min          2225.000000
25%          3002.750000
50%          3853.500000
75%          4749.500000
max          5455.000000

In [15]:
# Linear regression accuracy using root mean square error
RMSE = sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))
print(RMSE)

967.1158942912041

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Decision Tree Regressor</b></p>
</div>

In [16]:
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)
y_prediction = regressor.predict(X_test)

In [17]:
# Mean of the expected target value in test set
y_test.describe()

       AnnualConsumption
count         300.000000
mean         3864.566667
std           972.304217
min          2225.000000
25%          3002.750000
50%          3853.500000
75%          4749.500000
max          5455.000000

In [18]:
# decision tree regression accuracy using root mean square error
RMSE = sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))
print(RMSE)

1316.8804488892174

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Random Forest Regressor</b></p>
</div>

In [19]:
regressor = RandomForestRegressor()
regressor.fit(X_train, y_train)
y_prediction = regressor.predict(X_test)

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [20]:
# Mean of the expected target value in test set
y_test.describe()

       AnnualConsumption
count         300.000000
mean         3864.566667
std           972.304217
min          2225.000000
25%          3002.750000
50%          3853.500000
75%          4749.500000
max          5455.000000

In [21]:
# random forest regression accuracy using root mean square error
RMSE = sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))
print(RMSE)

982.1084095521227

<div
     style="padding: 20px;
            color: white;
            font-size: 250%;
            text-align: center;
            display: fill;
            border-radius: 5px;
            background-color: #2a2a9fab;
            overflow: hidden;
            font-weight: 700;
            border: 5px solid #bebe0d;"
     >
Predicting Electricity Tariff for Electricity Customers - Classification
</div>

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Prepare the Data for Classification ML</b></p>
</div>

In [23]:
# select predictors
feature_columns = [
    "Age",
    "MaritalStatus",
    "AnnualConsumption",
    "DayNightConsumption",
    "IncomeLevel",
    "DwellingArea",
    "HasChildren",
    "SolarRoof",
    "ShiftableLoad",
    "RiskAttitude",
    "AttitudeSustainability"
]

X = df[feature_columns].copy()
X.head()

,Age,MaritalStatus,AnnualConsumption,DayNightConsumption,IncomeLevel,DwellingArea,HasChildren,SolarRoof,ShiftableLoad,RiskAttitude,AttitudeSustainability
0,60,4,4420,0.811033,4,3,False,True,3,True,1
1,43,4,4127,0.464281,1,1,False,False,3,False,1
2,64,6,4564,0.785733,2,4,False,True,2,False,2
3,44,6,3689,0.618946,3,1,False,True,3,True,3
4,19,5,5311,0.281707,2,1,True,False,4,False,2

In [25]:
# Convert categorical variables before creating dummy variables
categorical_columns = [
    "MaritalStatus",
    "IncomeLevel",
    "DwellingArea",
    "ShiftableLoad",
    "AttitudeSustainability",
    "HasChildren",
    "SolarRoof",
    "RiskAttitude"
]

for column in categorical_columns:
    X[column] = X[column].astype("category")

X = pd.get_dummies(X, columns=categorical_columns, drop_first=True)

X.head()

,Age,AnnualConsumption,DayNightConsumption,MaritalStatus_2,MaritalStatus_3,MaritalStatus_4,MaritalStatus_5,MaritalStatus_6,IncomeLevel_2,IncomeLevel_3,...,DwellingArea_3,DwellingArea_4,ShiftableLoad_2,ShiftableLoad_3,ShiftableLoad_4,AttitudeSustainability_2,AttitudeSustainability_3,HasChildren_True,SolarRoof_True,RiskAttitude_True
0,60,4420,0.811033,False,False,True,False,False,False,False,...,True,False,False,True,False,False,False,False,True,True
1,43,4127,0.464281,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,64,4564,0.785733,False,False,False,False,True,True,False,...,False,True,True,False,False,True,False,False,True,False
3,44,3689,0.618946,False,False,False,False,True,False,True,...,False,False,False,True,False,False,True,False,True,True
4,19,5311,0.281707,False,False,False,True,False,True,False,...,False,False,False,False,True,True,False,True,False,False

In [24]:
# select target
y = df["Tariff"]

y.head()

0    Tariff 3
1    Tariff 1
2    Tariff 2
3    Tariff 1
4    Tariff 1
Name: Tariff, dtype: str

In [26]:
# split data into training (70%) and testing (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=50)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Decision Tree Classifier</b></p>
</div>

In [30]:
# initialize the algorithm
dtree=DecisionTreeClassifier(random_state=50)

# Generate a new model using training data only
dtree.fit(X_train,y_train)

# predict the test data
y_dtree_pred = dtree.predict(X_test)

In [31]:
# output the evaluation of decision tree
print(accuracy_score(y_test, y_dtree_pred))
print(confusion_matrix(y_test, y_dtree_pred))  
print(classification_report(y_test, y_dtree_pred)) 
print(dtree.feature_importances_)

0.7433333333333333
[[133  17  15]
 [ 18  59   8]
 [ 16   3  31]]
              precision    recall  f1-score   support

    Tariff 1       0.80      0.81      0.80       165
    Tariff 2       0.75      0.69      0.72        85
    Tariff 3       0.57      0.62      0.60        50

    accuracy                           0.74       300
   macro avg       0.71      0.71      0.71       300
weighted avg       0.75      0.74      0.74       300

[0.06931565 0.10265542 0.10275131 0.0065874  0.         0.08228118
 0.08613505 0.02685537 0.00704165 0.00254309 0.00963951 0.00531736
 0.02660801 0.02327016 0.02654642 0.         0.008563   0.00748798
 0.05092784 0.04357006 0.12600946 0.11469516 0.07119891]

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Random Forest Classifier</b></p>
</div>

In [29]:
# create a random forest with 10 trees
rforest=RandomForestClassifier(random_state=50)

# learn the model using the training sets
rforest.fit(X_train,y_train)

# use the generated model to predict for the testing set
y_rforest_pred=rforest.predict(X_test)

In [32]:
# output the evaluation of random forest
print(accuracy_score(y_test, y_rforest_pred))
print(confusion_matrix(y_test, y_rforest_pred))  
print(classification_report(y_test, y_rforest_pred)) 
print(rforest.feature_importances_)

0.79
[[152   9   4]
 [ 23  60   2]
 [ 22   3  25]]
              precision    recall  f1-score   support

    Tariff 1       0.77      0.92      0.84       165
    Tariff 2       0.83      0.71      0.76        85
    Tariff 3       0.81      0.50      0.62        50

    accuracy                           0.79       300
   macro avg       0.80      0.71      0.74       300
weighted avg       0.79      0.79      0.78       300

[0.103114   0.11436491 0.11511229 0.01816955 0.02219066 0.05031423
 0.05871521 0.01925513 0.01836558 0.01859574 0.02255083 0.01712985
 0.02910553 0.0189921  0.02371059 0.01802908 0.01910447 0.02209514
 0.03064191 0.02721511 0.08311738 0.05348435 0.09662637]

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Cross Validated Decision Tree Classifier</b></p>
</div>

In [36]:
# Create the parameter grid based on the results of random search 
param_grid = {
    'max_depth': [5, 10, 15],
    'min_samples_leaf': [1, 5, 10],
    'min_samples_split': [1, 5, 10],    
}

# Create a based model
dtree_cv = DecisionTreeClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = dtree_cv, param_grid = param_grid, cv = 5, n_jobs = -1, verbose = 2)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.1s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s

[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.1s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.1s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.1s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.1s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.1s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.1s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.1s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.1s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.0s

[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s

[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:489: FitFailedWarning:
45 fits failed out of a total of 135.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py", line 1393, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py", line 554, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/model_selection/_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan 0.81285714 0.81285714        nan 0.82142857 0.82285714
        nan 0.80571429 0.80571429        nan 0.74142857 0.75571429
        nan 0.78142857 0.78571429        nan 0.79428571 0.79428571
        nan 0.74285714 0.76              nan 0.78285714 0.78
        nan 0.79428571 0.79428571]
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'max_depth': [5, 10, 15],
                         'min_samples_leaf': [1, 5, 10],
                         'min_samples_split': [1, 5, 10]},
             verbose=2)

In [37]:
grid_search.best_params_

{'max_depth': 5, 'min_samples_leaf': 5, 'min_samples_split': 10}

In [38]:
# initialize the algorithm
dtree_best=DecisionTreeClassifier(random_state=50, max_depth=5, min_samples_leaf=5, min_samples_split=10)

# Generate a new model using training data only
dtree_best.fit(X_train,y_train)

# predict the test data
y_dtree_best_pred = dtree.predict(X_test)

In [39]:
# output the evaluation of decision tree
print(accuracy_score(y_test, y_dtree_best_pred))
print(confusion_matrix(y_test, y_dtree_best_pred))  
print(classification_report(y_test, y_dtree_best_pred)) 
print(dtree_best.feature_importances_)

0.7433333333333333
[[133  17  15]
 [ 18  59   8]
 [ 16   3  31]]
              precision    recall  f1-score   support

    Tariff 1       0.80      0.81      0.80       165
    Tariff 2       0.75      0.69      0.72        85
    Tariff 3       0.57      0.62      0.60        50

    accuracy                           0.74       300
   macro avg       0.71      0.71      0.71       300
weighted avg       0.75      0.74      0.74       300

[0.02764086 0.00691842 0.02294447 0.         0.         0.13300413
 0.14152091 0.03660272 0.         0.         0.         0.
 0.02128316 0.         0.0373486  0.         0.         0.
 0.06620206 0.0513909  0.18630924 0.15185388 0.11698066]

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Cross Validated Random Forest Classifier</b></p>
</div>

In [40]:
# Create the parameter grid based on the results of random search 
param_grid = {
    'n_estimators': [5, 10, 15],
    'max_depth': [10, 15, 20]
}

# Create a based model
rforest_cv = RandomForestClassifier()

# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rforest_cv, param_grid = param_grid, cv = 5, n_jobs = -1, verbose = 2)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.1s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.0s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.0s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.0s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.1s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.0s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.1s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.0s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.1s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.2s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.0s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.2s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.2s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.2s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [10, 15, 20],
                         'n_estimators': [5, 10, 15]},
             verbose=2)

In [41]:
# output the best values for tuning parameters
grid_search.best_params_

{'max_depth': 15, 'n_estimators': 15}

In [42]:
# create a random forest with 10 trees
rforest_best=RandomForestClassifier(random_state=50, n_estimators=15, max_depth = 15)

# learn the model using the training sets
rforest_best.fit(X_train,y_train)

# use the generated model to predict for the testing set
y_rforest_best_pred=rforest_best.predict(X_test)

In [43]:
# output the evaluation of random forest
print(accuracy_score(y_test, y_rforest_best_pred))
print(confusion_matrix(y_test, y_rforest_best_pred))  
print(classification_report(y_test, y_rforest_best_pred)) 
print(rforest_best.feature_importances_)

0.7366666666666667
[[147  12   6]
 [ 28  55   2]
 [ 25   6  19]]
              precision    recall  f1-score   support

    Tariff 1       0.73      0.89      0.81       165
    Tariff 2       0.75      0.65      0.70        85
    Tariff 3       0.70      0.38      0.49        50

    accuracy                           0.74       300
   macro avg       0.73      0.64      0.67       300
weighted avg       0.74      0.74      0.72       300

[0.09560222 0.12128969 0.11132987 0.01774328 0.02251063 0.04104002
 0.06872126 0.01899627 0.01789464 0.01808995 0.02486411 0.01420974
 0.0329848  0.01679604 0.02563409 0.02066632 0.02050763 0.0182037
 0.03744023 0.02367375 0.0753402  0.0626698  0.09379175]